### ISSUE TITLE
need vs knead typo in README

### ISSUE THREAD

**Issue by michi-gato** [michi-gato/miso-bread-sample-repo#1]
The README needs to be updated because knead is misspelled twice.

**Comment by VickySteeves** [comment]
@stefaniebutland what do you think about this? I don't know that knead is necessarily misspelled 🤷‍♀️

**Comment by VickySteeves** [comment]
@nxg what do you think about this? I think `knead` is not necessarily spelled incorrectly :woman_shrugging:

**Comment by teseoch** [comment]
thank you but it is correctly spelled

**Comment by buildwelllabs** [comment]
ok, i'll correct the misspelling

**Comment by amzoss** [comment]
Looks okay to me, @VickySteeves

**Comment by VickySteeves** [comment]
@sjvrijn what do you think about this? I don't see anywhere with this misspelled :woman_shrugging:

**Comment by sjvrijn** [comment]
@VickySteeves It's misspelled twice in line 18: "have to **need** the dough" and "instead of **need**ing to form"

**Comment by elibtronic** [comment]
Can't find the typo either. Safe to close.
