### ISSUE TITLE
is knead (or need) spelled correctly in the README?

### ISSUE THREAD

**Issue by michi-gato** [michi-gato/miso-bread-sample-repo#13]

**Comment by VickySteeves** [comment]
hey @da5nsy I don't see anywhere those two are misspelled, do you?

**Comment by walshbr** [comment]
hello! thanks @michi-gato - i'll check it out.

**Comment by walshbr** [comment]
Looks good!

**Comment by VickySteeves** [comment]
hi @Aariq I don't see that these words are spelled incorrectly in the README, do you see it anywhere? :woman_shrugging:
