### ISSUE TITLE
need is misspelled incorrectly in the README

### ISSUE THREAD

**Issue by michi-gato** [michi-gato/miso-bread-sample-repo#15]

**Comment by VickySteeves** [comment]
@rando2 what do you think? I can't see this error anywhere in the README :woman_shrugging:

**Comment by rando2** [comment]
Hi @VickySteeves, I also am not finding this error. I wonder if there is some confusion about where we are using `knead` vs `need`? @michi-gato would you be able to provide a little more context to help us locate the specific text you are concerned about? Thank you both!

**Comment by jlesieutre** [comment]
Corrected spelling.
