### ISSUE TITLE
check spelling of knead vs need

### ISSUE THREAD

**Issue by michi-gato** [michi-gato/miso-bread-sample-repo#6]
seems to be incorrect in a couple places. Please check, ty!

**Comment by VickySteeves** [comment]
@magland what do you think about this? I can't see anywhere that `knead` is misspelled :woman_shrugging:

**Comment by VickySteeves** [comment]
@plavskin what do you think? I don't see anywhere that `knead` is misspelled :woman_shrugging:

**Comment by duncdrum** [comment]
@michi-gato could you tell us the line and the filename where you found the wrong spelling please?
